

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
